version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    ports:
      - ${PGSQL_LOCAL_PORT}:5432
    environment:
      POSTGRES_DB: merchant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
